import * as THREE from 'three';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
import { OutputPass } from 'three/addons/postprocessing/OutputPass.js';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';
import { buildPlayerShip, buildEnemyModel, buildBossModel, buildPickup, mats, animateModel } from './models.js';

const $=s=>document.querySelector(s),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=THREE.MathUtils.lerp,rand=(a,b)=>a+Math.random()*(b-a),chance=p=>Math.random()<p;
const canvas=$('#game'),scoreEl=$('#score'),shieldBar=$('#shieldBar'),shieldText=$('#shieldText'),driveBar=$('#driveBar'),driveText=$('#driveText'),heatBar=$('#heatBar'),heatText=$('#heatText'),waveEl=$('#wave'),objectiveEl=$('#objective'),bossWrap=$('#bossWrap'),bossBar=$('#bossBar'),bossName=$('#bossName'),comboEl=$('#combo'),reticle=$('#reticle'),start=$('#start'),gameover=$('#gameover'),finalScore=$('#finalScore'),fireBtn=$('#fire'),dashBtn=$('#dash'),stickZone=$('#stickZone'),stickKnob=$('#stickKnob'),flash=$('#flash'),damage=$('#damage'),toast=$('#toast'),qualityEl=$('#quality');
const isCoarse=matchMedia('(pointer: coarse)').matches,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const PLAYER_VISUAL_SCALE=isCoarse?.46:.72,PLAYER_BASE_Y=isCoarse?-.55:.35,PLAYER_BASE_Z=isCoarse?2.15:3.0,PLAYER_Y_RANGE=isCoarse?3.15:4.15;
const renderer=new THREE.WebGLRenderer({canvas,antialias:false,powerPreference:'high-performance',alpha:false,depth:true,stencil:false});renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;const gl2=renderer.capabilities.isWebGL2;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x050915);scene.fog=new THREE.FogExp2(0x091629,.0108);const camera=new THREE.PerspectiveCamera(isCoarse?69:64,1,.08,440);camera.position.set(0,isCoarse?5.6:5.0,isCoarse?15.8:14.2);
const pmrem=new THREE.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(new RoomEnvironment(),.035).texture;pmrem.dispose();
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));const bloom=new UnrealBloomPass(new THREE.Vector2(1,1),.78,.6,.7);composer.addPass(bloom);composer.addPass(new OutputPass());
scene.add(new THREE.HemisphereLight(0xa7ddff,0x12101d,1.25));const sun=new THREE.DirectionalLight(0xffeed8,3.45);sun.position.set(-23,35,19);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-30;sun.shadow.camera.right=30;sun.shadow.camera.top=30;sun.shadow.camera.bottom=-30;sun.shadow.camera.near=.1;sun.shadow.camera.far=110;sun.shadow.bias=-.00035;scene.add(sun);const rim=new THREE.PointLight(0x5b6cff,19,48,2);rim.position.set(15,9,-12);scene.add(rim);
const scenery=new THREE.Group();scene.add(scenery);const actors=new THREE.Group();scene.add(actors);const fx=new THREE.Group();scene.add(fx);const enemies=[],projectiles=[],enemyShots=[],pickups=[],debris=[],pulseRings=[];const clock=new THREE.Clock();
const state={running:false,score:0,shield:100,drive:100,heat:0,overheated:false,wave:1,kills:0,targetKills:8,combo:1,comboT:0,fire:false,dashCD:0,dashT:0,time:0,speed:15,shake:0,quality:1,avgFps:60,sampleT:0,sampleFrames:0,spawnT:0,spawnRemaining:0,lastHitT:99,boss:null,bossPhase:0,overclockT:0,mission:'intercept',waveClearing:false,nearMisses:0};
const input={x:0,y:0,keyX:0,keyY:0,pointer:null};
function makeSky(){const geo=new THREE.SphereGeometry(220,34,20),mat=new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,uniforms:{uTime:{value:0},uTop:{value:new THREE.Color(0x061023)},uHorizon:{value:new THREE.Color(0x365887)},uGlow:{value:new THREE.Color(0x91e8ff)}},vertexShader:`varying vec3 vW;void main(){vec4 w=modelMatrix*vec4(position,1.);vW=w.xyz;gl_Position=projectionMatrix*viewMatrix*w;}`,fragmentShader:`uniform float uTime;uniform vec3 uTop,uHorizon,uGlow;varying vec3 vW;float n(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}void main(){vec3 d=normalize(vW-cameraPosition);float h=clamp(d.y*.56+.46,0.,1.);vec3 c=mix(uHorizon,uTop,smoothstep(.0,.75,h));float sun=pow(max(dot(d,normalize(vec3(-.42,.36,-.5))),0.),30.);float haze=pow(1.-abs(d.y),5.);float stars=step(.9975,n(floor((d.xz+uTime*.0003)*950.)))*smoothstep(.45,.9,h);c+=uGlow*sun*.9+vec3(.15,.28,.52)*haze*.32+stars*.5;gl_FragColor=vec4(c,1.);}`});const mesh=new THREE.Mesh(geo,mat);mesh.frustumCulled=false;scene.add(mesh);return mesh}const sky=makeSky();
function makeOcean(){const seg=isCoarse?56:78,geo=new THREE.PlaneGeometry(380,380,seg,seg);geo.rotateX(-Math.PI/2);const mat=new THREE.ShaderMaterial({uniforms:{uTime:{value:0},uC1:{value:new THREE.Color(0x07172b)},uC2:{value:new THREE.Color(0x1a5276)},uGlow:{value:new THREE.Color(0x66eaff)}},vertexShader:`uniform float uTime;varying float vH;varying vec3 vW;void main(){vec3 p=position;float w=sin(p.x*.075+uTime*.68)*1.05+sin(p.z*.105-uTime*.5)*.72+sin((p.x+p.z)*.043+uTime*.92)*.52;p.y+=w;vH=w;vec4 wp=modelMatrix*vec4(p,1.);vW=wp.xyz;gl_Position=projectionMatrix*viewMatrix*wp;}`,fragmentShader:`uniform float uTime;uniform vec3 uC1,uC2,uGlow;varying float vH;varying vec3 vW;void main(){vec3 V=normalize(cameraPosition-vW);float fres=pow(1.-abs(V.y),3.2);float band=.5+.5*sin(vW.x*.035+vW.z*.047+uTime*.35);vec3 c=mix(uC1,uC2,clamp(vH*.12+.5,0.,1.));c+=uGlow*(fres*.19+band*.024);gl_FragColor=vec4(c,1.);}`});const mesh=new THREE.Mesh(geo,mat);mesh.position.y=-12;scene.add(mesh);return mesh}const ocean=makeOcean();
function makeClouds(){const geo=new THREE.PlaneGeometry(320,220,1,1),mat=new THREE.ShaderMaterial({transparent:true,depthWrite:false,side:THREE.DoubleSide,uniforms:{uTime:{value:0}},vertexShader:`varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`uniform float uTime;varying vec2 vUv;float h(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float n(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(h(i),h(i+vec2(1,0)),f.x),mix(h(i+vec2(0,1)),h(i+vec2(1,1)),f.x),f.y);}float fb(vec2 p){float v=0.,a=.5;for(int i=0;i<4;i++){v+=a*n(p);p*=2.03;a*=.5;}return v;}void main(){vec2 p=vUv*5.;p.x+=uTime*.012;float q=fb(p)+.5*fb(p*1.7+3.);float a=smoothstep(.58,.85,q)*.2;vec3 c=mix(vec3(.16,.28,.42),vec3(.42,.62,.78),q);gl_FragColor=vec4(c,a);}`});const m=new THREE.Mesh(geo,mat);m.rotation.x=-Math.PI/2;m.position.set(0,27,-70);scene.add(m);return m}const clouds=makeClouds();
function makeDust(){const n=isCoarse?650:1150,pos=new Float32Array(n*3),size=new Float32Array(n);for(let i=0;i<n;i++){pos[i*3]=rand(-68,68);pos[i*3+1]=rand(-8,36);pos[i*3+2]=rand(-160,28);size[i]=rand(.65,2.1)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(pos,3));g.setAttribute('aSize',new THREE.BufferAttribute(size,1));const m=new THREE.ShaderMaterial({transparent:true,depthWrite:false,blending:THREE.AdditiveBlending,uniforms:{uPixel:{value:1},uTime:{value:0}},vertexShader:`attribute float aSize;uniform float uPixel,uTime;varying float vA;void main(){vec3 p=position;p.z=mod(p.z+uTime*13.+160.,188.)-160.;vec4 mv=modelViewMatrix*vec4(p,1.);gl_Position=projectionMatrix*mv;gl_PointSize=aSize*uPixel*(90./-mv.z);vA=smoothstep(170.,18.,-mv.z);}`,fragmentShader:`varying float vA;void main(){vec2 p=gl_PointCoord-.5;float d=dot(p,p);if(d>.25)discard;gl_FragColor=vec4(.55,.9,1.,smoothstep(.25,0.,d)*vA*.5);}`});const pts=new THREE.Points(g,m);pts.frustumCulled=false;scene.add(pts);return pts}const dust=makeDust();
const rockMat=new THREE.MeshStandardMaterial({color:0x263850,metalness:.12,roughness:.76}),ruinMat=new THREE.MeshStandardMaterial({color:0x101c2e,metalness:.7,roughness:.38});
function buildScenery(){const count=isCoarse?46:70,dummy=new THREE.Object3D(),rocks=new THREE.InstancedMesh(new THREE.IcosahedronGeometry(1,1),rockMat,count*3);rocks.castShadow=true;rocks.receiveShadow=true;let idx=0;for(let i=0;i<count;i++){const side=i%2?-1:1,x=side*rand(11,44),z=-i*rand(5.1,7.4)-8,y=rand(-8,11),s=rand(1.6,5.3);for(let k=0;k<3;k++){dummy.position.set(x+rand(-s,s),y+rand(-2,2),z+rand(-3,3));dummy.scale.set(rand(.7,2.1)*s,rand(.55,1.65)*s,rand(.75,2)*s);dummy.rotation.set(rand(0,3),rand(0,3),rand(0,3));dummy.updateMatrix();rocks.setMatrixAt(idx++,dummy.matrix)}}rocks.count=idx;scenery.add(rocks);const pylons=new THREE.InstancedMesh(new THREE.BoxGeometry(1,1,1),ruinMat,count);pylons.castShadow=true;idx=0;for(let i=0;i<count;i++){const side=i%2?-1:1;dummy.position.set(side*rand(13,31),rand(-3,12),-i*6.4-rand(6,16));dummy.scale.set(rand(.45,1.2),rand(3,13),rand(.45,1.3));dummy.rotation.y=rand(-.55,.55);dummy.updateMatrix();pylons.setMatrixAt(idx++,dummy.matrix)}scenery.add(pylons);for(let i=0;i<8;i++){const radius=rand(4.5,7),ring=new THREE.Mesh(new THREE.TorusGeometry(radius,.22,8,36),mats.hullDark);ring.position.set((i%2?-1:1)*rand(13,25),rand(2,15),-45-i*42);ring.rotation.set(rand(-.5,.5),rand(-.5,.5),rand(-.5,.5));ring.castShadow=true;scenery.add(ring);const core=new THREE.Mesh(new THREE.TorusGeometry(radius*.72,.07,6,32),i%2?mats.cyan:mats.gold);core.position.copy(ring.position);core.rotation.copy(ring.rotation);scenery.add(core)}}buildScenery();
const ship=buildPlayerShip();ship.scale.setScalar(PLAYER_VISUAL_SCALE);ship.position.set(0,PLAYER_BASE_Y,PLAYER_BASE_Z);scene.add(ship);
const shotGeo=new THREE.CylinderGeometry(.055,.095,1.9,7);shotGeo.rotateX(Math.PI/2);const playerShotMat=new THREE.MeshBasicMaterial({color:0xff78b8,transparent:true,opacity:.98,blending:THREE.AdditiveBlending,depthWrite:false}),enemyShotMat=new THREE.MeshBasicMaterial({color:0xffa34f,transparent:true,opacity:.94,blending:THREE.AdditiveBlending,depthWrite:false}),enemyShotHotMat=new THREE.MeshBasicMaterial({color:0xff487f,transparent:true,opacity:.96,blending:THREE.AdditiveBlending,depthWrite:false}),enemyOrbGeo=new THREE.SphereGeometry(.16,8,6),enemyTankOrbGeo=new THREE.SphereGeometry(.21,8,6),debrisGeo=new THREE.TetrahedronGeometry(.14),tmpA=new THREE.Vector3();
const ENEMY_STATS={scout:{hp:2,speed:1.12,fire:[1.45,2.6],score:260,damage:9},striker:{hp:5,speed:.92,fire:[.9,1.65],score:520,damage:12},tank:{hp:10,speed:.67,fire:[1.15,1.9],score:900,damage:15}};
function disposeActorGeometry(root){root.traverse(o=>{if(o.isMesh&&o.geometry)o.geometry.dispose()})}
function makeEnemy(type='scout',z=-90,x=rand(-9,9),y=rand(-2.5,7.5)){const g=buildEnemyModel(type),s=ENEMY_STATS[type];g.position.set(x,y,z);g.rotation.order='YXZ';g.userData={...g.userData,type,hp:s.hp,maxHp:s.hp,phase:rand(0,6.28),fire:rand(...s.fire),baseX:x,baseY:y,dead:false,passed:false};actors.add(g);enemies.push(g);return g}
function makeBoss(){const g=buildBossModel();g.position.set(0,4,-105);const hp=55+state.wave*9;g.userData={...g.userData,type:'boss',hp,maxHp:hp,phase:0,fire:1.2,special:2.8,dead:false,baseX:0,baseY:4};actors.add(g);enemies.push(g);state.boss=g;state.bossPhase=1;bossWrap.classList.add('show');bossName.textContent='HARBINGER CARRIER';return g}
function spawnFormation(){if(state.spawnRemaining<=0||state.boss||enemies.length>=8)return;const w=state.wave,pattern=Math.floor(rand(0,4)),z=-95-rand(0,22),slots=Math.min(state.spawnRemaining,pattern===3?4:3);if(pattern===0){for(let i=0;i<slots;i++){const type=w>2&&i===1?'striker':'scout';makeEnemy(type,z-i*6,(i-(slots-1)/2)*4,rand(-.2,5));state.spawnRemaining--}}else if(pattern===1){for(let i=0;i<slots;i++){const s=i%2?-1:1;makeEnemy('scout',z-i*4,s*(2.5+i*1.8),1+i*.8);state.spawnRemaining--}}else if(pattern===2&&w>=3){makeEnemy('tank',z,rand(-5,5),rand(1,5));state.spawnRemaining--;for(let i=1;i<slots;i++){makeEnemy('scout',z-4*i,(i%2?-1:1)*4.5,rand(0,5));state.spawnRemaining--}}else{for(let i=0;i<slots;i++){const type=w>=2&&chance(.55)?'striker':'scout';makeEnemy(type,z-i*5,rand(-8,8),rand(-2,7));state.spawnRemaining--}}state.spawnT=rand(1.1,1.8)}
function beginWave(){state.waveClearing=false;state.kills=0;state.boss=null;state.bossPhase=0;bossWrap.classList.remove('show');waveEl.textContent=String(state.wave).padStart(2,'0');if(state.wave%4===0){state.mission='boss';state.targetKills=1;state.spawnRemaining=0;objectiveEl.textContent='DESTROY THE HARBINGER';makeBoss();toastMsg('BOSS SIGNAL ACQUIRED')}else{state.mission='intercept';state.targetKills=7+state.wave*2;state.spawnRemaining=state.targetKills;objectiveEl.textContent=`0 / ${state.targetKills} HOSTILES`;spawnFormation();toastMsg(state.wave===1?'INTERCEPTOR ONLINE':`WAVE ${String(state.wave).padStart(2,'0')}`)}}
function queueNextWave(){if(state.waveClearing)return;state.waveClearing=true;state.wave++;toastMsg('AIRSPACE CLEARED');setTimeout(()=>{if(state.running)beginWave()},1050)}
function shoot(){if(!state.running||state.overheated)return;const rateBoost=state.overclockT>0?1.35:1;state.heat=clamp(state.heat+3.9/rateBoost,0,110);if(state.heat>=100){state.overheated=true;state.fire=false;fireBtn.classList.remove('active');toastMsg('CANNONS OVERHEATED');blip(75,.2,.07,'sawtooth');return}for(const muzzle of ship.userData.muzzles){muzzle.getWorldPosition(tmpA);const p=new THREE.Mesh(shotGeo,playerShotMat);p.position.copy(tmpA);p.userData={life:1.6,vel:new THREE.Vector3((input.x+input.keyX)*2.5,(input.y+input.keyY)*1.4,-78),damage:state.overclockT>0?1.35:1};fx.add(p);projectiles.push(p)}blip(state.overclockT>0?620:540,.026,.022,'sawtooth')}
function enemyShoot(e,spread=0){const count=e.userData.type==='striker'?2:1;for(let n=0;n<count;n++){const p=new THREE.Mesh(e.userData.type==='tank'?enemyTankOrbGeo:enemyOrbGeo,e.userData.type==='tank'?enemyShotHotMat:enemyShotMat);p.position.copy(e.position);const speed=18+state.wave*.7+(e.userData.type==='striker'?3:0),aim=ship.position.clone().sub(e.position).normalize();aim.x+=spread+((n-(count-1)/2)*.08);aim.y+=rand(-.025,.025);aim.normalize().multiplyScalar(speed);p.userData={life:5,vel:aim,damage:ENEMY_STATS[e.userData.type]?.damage||12,near:false};fx.add(p);enemyShots.push(p)}}
function bossVolley(b){if(state.bossPhase===1){for(const s of [-.16,0,.16])enemyShoot(b,s)}else if(state.bossPhase===2){for(let i=0;i<7;i++){const a=(i/6-.5)*.64,p=new THREE.Mesh(enemyTankOrbGeo,enemyShotHotMat);p.position.copy(b.position);const aim=ship.position.clone().sub(b.position).normalize().multiplyScalar(22);aim.x+=Math.sin(a)*8;aim.y+=Math.sin(a*.7)*3;p.userData={life:5,vel:aim,damage:13,near:false};fx.add(p);enemyShots.push(p)}}else{for(let i=0;i<10;i++){const a=(i/10)*Math.PI*2,p=new THREE.Mesh(enemyOrbGeo,i%2?enemyShotMat:enemyShotHotMat);p.position.copy(b.position);const aim=ship.position.clone().sub(b.position).normalize().multiplyScalar(17);aim.x+=Math.cos(a)*8;aim.y+=Math.sin(a)*6;p.userData={life:5,vel:aim,damage:14,near:false};fx.add(p);enemyShots.push(p)}}}
function spawnPickup(pos,forced=null){const kind=forced||(state.shield<45?'shield':chance(.48)?'drive':'overclock'),p=buildPickup(kind);p.position.copy(pos);p.position.z-=1.5;p.userData={...p.userData,life:9,spin:rand(.7,1.4),baseY:p.position.y};actors.add(p);pickups.push(p)}
function collectPickup(p){const k=p.userData.kind;if(k==='shield'){state.shield=clamp(state.shield+28,0,100);toastMsg('SHIELD +28')}else if(k==='drive'){state.drive=clamp(state.drive+38,0,100);toastMsg('PHASE DRIVE +38')}else{state.overclockT=7;state.heat=Math.max(0,state.heat-35);toastMsg('WEAPON OVERCLOCK')}state.score+=180;actors.remove(p);disposeActorGeometry(p);const i=pickups.indexOf(p);if(i>=0)pickups.splice(i,1);navigator.vibrate?.(12);blip(k==='shield'?420:k==='drive'?650:820,.09,.05,'triangle')}
function explode(pos,hot=false,big=false){const count=isCoarse?(big?16:8):(big?28:14);for(let i=0;i<count;i++){const mat=hot?(i%3===0?mats.gold:mats.hot):mats.cyan,m=new THREE.Mesh(debrisGeo,mat);m.scale.setScalar(rand(.45,big?2.2:1.25));m.position.copy(pos);m.userData={life:rand(.35,big?1.2:.8),vel:new THREE.Vector3(rand(big?-10:-6,big?10:6),rand(big?-8:-5,big?8:5),rand(-4,big?12:8)),spin:new THREE.Vector3(rand(-9,9),rand(-9,9),rand(-9,9))};fx.add(m);debris.push(m)}state.shake=Math.max(state.shake,big?.8:.38);flash.style.opacity=big?.9:.62;setTimeout(()=>flash.style.opacity=0,big?110:65);blip(big?58:(hot?95:155),big?.22:.12,big?.12:.075,'square')}
function applyEnemyDamage(e,amount,critical=false){if(e.userData.dead)return;e.userData.hp-=amount*(critical?1.75:1);if(critical){state.score+=60;toastMsg('CORE HIT');blip(920,.045,.035,'triangle')}if(e.userData.type==='boss'){const ratio=clamp(e.userData.hp/e.userData.maxHp,0,1);bossBar.style.transform=`scaleX(${ratio})`;const phase=ratio>.66?1:ratio>.33?2:3;if(phase!==state.bossPhase){state.bossPhase=phase;toastMsg(`HARBINGER PHASE ${phase}`);explode(e.position,true,false);if(phase>1){for(let i=0;i<2;i++)makeEnemy('scout',e.position.z-8-i*6,(i?1:-1)*5,e.position.y-1)}}}if(e.userData.hp<=0)killEnemy(e)}
function killEnemy(e){if(e.userData.dead)return;e.userData.dead=true;const type=e.userData.type,base=type==='boss'?7000:ENEMY_STATS[type].score;state.combo=Math.min(8,state.combo+(type==='boss'?1.5:.35));state.comboT=2.6;state.score+=Math.round(base*state.combo);state.drive=clamp(state.drive+(type==='boss'?45:type==='tank'?18:10),0,100);state.kills++;explode(e.position,true,type==='boss');if(type!=='boss'&&chance(.16+(state.shield<40?.12:0)))spawnPickup(e.position);actors.remove(e);disposeActorGeometry(e);const i=enemies.indexOf(e);if(i>=0)enemies.splice(i,1);if(type==='boss'){state.boss=null;bossWrap.classList.remove('show');objectiveEl.textContent='HARBINGER DESTROYED';queueNextWave()}else{objectiveEl.textContent=`${state.kills} / ${state.targetKills} HOSTILES`;if(state.kills>=state.targetKills&&state.spawnRemaining<=0&&enemies.length===0)queueNextWave()}toastMsg(type==='boss'?'HARBINGER DESTROYED':`COMBO ×${state.combo.toFixed(1)}`)}
function hurt(amount){if(state.dashT>0)return;state.shield-=amount;state.lastHitT=0;state.combo=Math.max(1,state.combo-.8);state.comboT=0;state.shake=.82;damage.style.opacity=.9;setTimeout(()=>damage.style.opacity=0,120);navigator.vibrate?.(28);blip(62,.12,.1,'sawtooth');if(state.shield<=0)endGame()}
function updateEnemies(dt){if(state.spawnT>0)state.spawnT-=dt;if(state.mission==='intercept'&&state.spawnRemaining>0&&state.spawnT<=0&&enemies.length<7)spawnFormation();for(let i=enemies.length-1;i>=0;i--){const e=enemies[i],u=e.userData;u.phase+=dt;if(u.type==='boss'){const ratio=clamp(u.hp/u.maxHp,0,1);e.position.z=lerp(e.position.z,-27,dt*.45);e.position.x=lerp(e.position.x,Math.sin(u.phase*.55)*5.2,dt*.75);e.position.y=lerp(e.position.y,3.8+Math.cos(u.phase*.7)*1.3,dt*.8);e.rotation.z=Math.sin(u.phase*.6)*.08;animateModel(e,dt,state.time,1.2);u.fire-=dt;u.special-=dt;if(e.position.z>-55&&u.fire<=0){bossVolley(e);u.fire=state.bossPhase===3?.72:state.bossPhase===2?1:1.3}if(e.position.z>-50&&u.special<=0){if(state.bossPhase>=2&&enemies.filter(x=>x!==e).length<3){makeEnemy(state.bossPhase===3?'striker':'scout',e.position.z-9,rand(-7,7),rand(-1,7));makeEnemy('scout',e.position.z-14,rand(-7,7),rand(-1,7))}u.special=state.bossPhase===3?3.2:4.4}bossBar.style.transform=`scaleX(${ratio})`;continue}const s=ENEMY_STATS[u.type];e.position.z+=state.speed*dt*.72*s.speed;const amp=u.type==='striker'?4.2:u.type==='tank'?1.6:2.8;e.position.x=lerp(e.position.x,u.baseX+Math.sin(u.phase*(u.type==='striker'?1.7:1.15))*amp,dt*(u.type==='tank'?1.05:1.8));e.position.y=lerp(e.position.y,u.baseY+Math.cos(u.phase*(u.type==='scout'?1.1:.75))*(u.type==='tank'?.8:1.45),dt*1.6);e.rotation.z=lerp(e.rotation.z,-Math.cos(u.phase*1.2)*(u.type==='striker'?.3:.16),dt*2.2);e.rotation.y=Math.sin(u.phase*.7)*.1;animateModel(e,dt,state.time,1);u.fire-=dt;if(u.fire<0&&e.position.z>-72&&e.position.z<-8){enemyShoot(e);u.fire=rand(...s.fire)*Math.max(.55,1-state.wave*.025)}if(e.position.z>13){actors.remove(e);disposeActorGeometry(e);enemies.splice(i,1);hurt(s.damage);state.spawnRemaining++}}const target=enemies.filter(e=>e.position.z<3&&e.position.z>-75).sort((a,b)=>a.position.distanceToSquared(ship.position)-b.position.distanceToSquared(ship.position))[0],locked=!!target&&target.position.distanceTo(ship.position)<48;reticle.classList.toggle('lock',locked)}
function updateProjectiles(dt){for(let i=projectiles.length-1;i>=0;i--){const p=projectiles[i];p.userData.life-=dt;p.position.addScaledVector(p.userData.vel,dt);let hit=null,critical=false;for(const e of enemies){const r=e.userData.hitRadius||1,d2=p.position.distanceToSquared(e.position);if(d2<r*r){hit=e;critical=d2<(r*.38)*(r*.38);break}}if(hit){applyEnemyDamage(hit,p.userData.damage,critical);fx.remove(p);projectiles.splice(i,1);continue}if(p.userData.life<=0||p.position.z<-145){fx.remove(p);projectiles.splice(i,1)}}for(let i=enemyShots.length-1;i>=0;i--){const p=enemyShots[i];p.userData.life-=dt;p.position.addScaledVector(p.userData.vel,dt);p.scale.setScalar(1+Math.sin(state.time*15+i)*.12);const d2=p.position.distanceToSquared(ship.position);if(d2<1.1){fx.remove(p);enemyShots.splice(i,1);hurt(p.userData.damage);continue}if(!p.userData.near&&d2<8&&p.position.z>ship.position.z){p.userData.near=true;state.nearMisses++;state.score+=35;state.drive=clamp(state.drive+2.5,0,100)}if(p.userData.life<=0||p.position.z>28||Math.abs(p.position.x)>40){fx.remove(p);enemyShots.splice(i,1)}}for(let i=debris.length-1;i>=0;i--){const d=debris[i],u=d.userData;u.life-=dt;d.position.addScaledVector(u.vel,dt);u.vel.y-=5*dt;d.rotation.x+=u.spin.x*dt;d.rotation.y+=u.spin.y*dt;d.rotation.z+=u.spin.z*dt;d.scale.multiplyScalar(.985);if(u.life<=0){fx.remove(d);debris.splice(i,1)}}}
function updatePickups(dt){for(let i=pickups.length-1;i>=0;i--){const p=pickups[i],u=p.userData;u.life-=dt;p.position.z+=state.speed*dt*.7;p.position.y=u.baseY+Math.sin(state.time*2.2+i)*.45;p.rotation.y+=dt*u.spin;p.rotation.z+=dt*.7;animateModel(p,dt,state.time,1);if(p.position.distanceToSquared(ship.position)<2.4){collectPickup(p);continue}if(u.life<=0||p.position.z>15){actors.remove(p);disposeActorGeometry(p);pickups.splice(i,1)}}}
function spawnPulseRing(){const ring=new THREE.Mesh(new THREE.TorusGeometry(1,.06,8,54),new THREE.MeshBasicMaterial({color:0x82faff,transparent:true,opacity:.9,blending:THREE.AdditiveBlending,depthWrite:false}));ring.position.copy(ship.position);ring.rotation.x=Math.PI/2;ring.userData={life:.55};fx.add(ring);pulseRings.push(ring)}
function updatePulses(dt){for(let i=pulseRings.length-1;i>=0;i--){const r=pulseRings[i];r.userData.life-=dt;const p=1-r.userData.life/.55;r.scale.setScalar(1+p*9);r.material.opacity=(1-p)*.8;if(r.userData.life<=0){fx.remove(r);r.geometry.dispose();r.material.dispose();pulseRings.splice(i,1)}}}
function updateShip(dt){const ix=clamp(input.x+input.keyX,-1,1),iy=clamp(input.y+input.keyY,-1,1),tx=ix*(isCoarse?7.6:8.5),ty=iy*PLAYER_Y_RANGE+PLAYER_BASE_Y;ship.position.x=lerp(ship.position.x,clamp(tx,-9,9),1-Math.pow(.0005,dt));ship.position.y=lerp(ship.position.y,clamp(ty,isCoarse?-3.4:-3.8,isCoarse?5.25:7.0),1-Math.pow(.001,dt));ship.rotation.z=lerp(ship.rotation.z,-ix*.42,dt*6.5);ship.rotation.x=lerp(ship.rotation.x,iy*.13,dt*5);ship.rotation.y=lerp(ship.rotation.y,-ix*.09,dt*5);ship.traverse(c=>{if(c.userData?.flame){const boost=state.dashT>0?1.85:(state.fire?1.16:1);c.scale.y=lerp(c.scale.y,boost,dt*12);c.material.opacity=isCoarse?.4:.54+Math.random()*(isCoarse?.18:.34)}});if(state.dashT>0){state.dashT-=dt;state.speed=lerp(state.speed,32,dt*8)}else state.speed=lerp(state.speed,15+state.wave*.28,dt*2.4);if(state.dashCD>0)state.dashCD-=dt;state.drive=clamp(state.drive+dt*(state.lastHitT>5?4:3),0,100);state.lastHitT+=dt;if(state.lastHitT>5.5&&state.shield<100)state.shield=clamp(state.shield+dt*2.1,0,100);if(state.overclockT>0)state.overclockT-=dt}
let fireAccumulator=0;function updateCombat(dt){const cooling=state.fire&&!state.overheated?12:state.overheated?34:23;state.heat=clamp(state.heat-dt*cooling,0,110);if(state.overheated&&state.heat<38){state.overheated=false;toastMsg('CANNONS READY')}if(state.fire&&!state.overheated){fireAccumulator-=dt;if(fireAccumulator<=0){shoot();fireAccumulator=state.overclockT>0?.073:.105}}else fireAccumulator=0;if(state.comboT>0)state.comboT-=dt;else state.combo=lerp(state.combo,1,dt*2.2)}
function updateCamera(dt){const target=new THREE.Vector3(ship.position.x*(isCoarse?.12:.18),ship.position.y*(isCoarse?.12:.22)+(isCoarse?5.7:4.9),isCoarse?15.8:14.2);camera.position.lerp(target,1-Math.pow(.002,dt));camera.fov=lerp(camera.fov,state.dashT>0?(isCoarse?74:70):(isCoarse?69:64),dt*5);camera.updateProjectionMatrix();camera.lookAt(new THREE.Vector3(ship.position.x*(isCoarse?.07:.11),ship.position.y*(isCoarse?.05:.12),isCoarse?-15:-12));if(state.shake>0&&!reduced){state.shake=Math.max(0,state.shake-dt*2.8);camera.position.x+=rand(-1,1)*state.shake*.16;camera.position.y+=rand(-1,1)*state.shake*.13}}
function updateQuality(dt){state.sampleT+=dt;state.sampleFrames++;if(state.sampleT>2.2){const fps=state.sampleFrames/state.sampleT;state.avgFps=lerp(state.avgFps,fps,.45);state.sampleT=0;state.sampleFrames=0;if(state.avgFps<41&&state.quality>.62)state.quality-=.08;else if(state.avgFps>56&&state.quality<1)state.quality+=.035;state.quality=clamp(state.quality,.58,1);applyQuality()}}let lastRatio=0;function applyQuality(){const base=Math.min(devicePixelRatio||1,isCoarse?1.7:2),ratio=base*state.quality;if(Math.abs(ratio-lastRatio)>.04){renderer.setPixelRatio(ratio);composer.setPixelRatio(ratio);lastRatio=ratio}bloom.enabled=state.quality>.64;bloom.strength=(isCoarse?.28:.42)+state.quality*(isCoarse?.26:.38);renderer.shadowMap.enabled=state.quality>.68;qualityEl.textContent=`${gl2?'WebGL2':'WebGL'} · ${Math.round(state.avgFps)} FPS · ${Math.round(state.quality*100)}%`}
function updateWorld(dt){scenery.position.z+=state.speed*dt*.055;if(scenery.position.z>7)scenery.position.z=0;sky.material.uniforms.uTime.value=state.time;ocean.material.uniforms.uTime.value=state.time;clouds.material.uniforms.uTime.value=state.time;dust.material.uniforms.uTime.value=state.time;dust.material.uniforms.uPixel.value=renderer.getPixelRatio()}
function updateHud(){scoreEl.textContent=String(Math.floor(state.score)).padStart(6,'0');shieldBar.style.transform=`scaleX(${clamp(state.shield/100,0,1)})`;shieldText.textContent=Math.max(0,Math.round(state.shield));driveBar.style.transform=`scaleX(${state.drive/100})`;driveText.textContent=Math.round(state.drive);heatBar.style.transform=`scaleX(${clamp(state.heat/100,0,1)})`;heatText.textContent=state.overheated?'HOT':Math.round(state.heat);heatBar.classList.toggle('hot',state.heat>75);dashBtn.style.opacity=state.drive>=35&&state.dashCD<=0?'1':'.42';comboEl.textContent=state.combo>1.08?`×${state.combo.toFixed(1)}`:'';comboEl.classList.toggle('show',state.combo>1.08)}
function toastMsg(text){toast.textContent=text;toast.animate([{opacity:0,transform:'translate(-50%,-6px) scale(.94)'},{opacity:1,transform:'translate(-50%,0) scale(1)',offset:.15},{opacity:1,offset:.62},{opacity:0,transform:'translate(-50%,10px) scale(1.05)'}],{duration:950,easing:'ease-out'})}
let audioCtx=null;function audio(){if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();return audioCtx}function blip(freq=200,dur=.05,gain=.04,type='sine'){try{const c=audio(),o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.setValueAtTime(freq,c.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(35,freq*.65),c.currentTime+dur);g.gain.setValueAtTime(gain,c.currentTime);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+dur);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+dur)}catch{}}
function clearActors(){for(const e of [...enemies]){actors.remove(e);disposeActorGeometry(e)}enemies.length=0;for(const p of [...pickups]){actors.remove(p);disposeActorGeometry(p)}pickups.length=0;for(const p of [...projectiles,...enemyShots,...debris])fx.remove(p);for(const r of [...pulseRings]){fx.remove(r);r.geometry.dispose();r.material.dispose()}projectiles.length=enemyShots.length=debris.length=pulseRings.length=0}
function startGame(){clearActors();Object.assign(state,{running:true,score:0,shield:100,drive:100,heat:0,overheated:false,wave:1,kills:0,targetKills:8,combo:1,comboT:0,fire:false,dashCD:0,dashT:0,time:0,speed:15,shake:0,spawnT:0,spawnRemaining:0,lastHitT:99,boss:null,bossPhase:0,overclockT:0,mission:'intercept',waveClearing:false,nearMisses:0});ship.visible=true;ship.scale.setScalar(PLAYER_VISUAL_SCALE);ship.position.set(0,PLAYER_BASE_Y,PLAYER_BASE_Z);ship.rotation.set(0,0,0);input.x=input.y=0;start.classList.add('hidden');gameover.classList.remove('show');bossWrap.classList.remove('show');audio();beginWave();navigator.vibrate?.(16)}
function endGame(){if(!state.running)return;state.running=false;state.fire=false;state.overheated=false;ship.visible=false;finalScore.firstChild.nodeValue=String(Math.floor(state.score));gameover.classList.add('show');bossWrap.classList.remove('show');navigator.vibrate?.([45,40,70]);explode(ship.position,true,true)}
function pulse(){if(!state.running||state.drive<35||state.dashCD>0)return;state.drive-=35;state.dashT=.48;state.dashCD=.9;state.shield=clamp(state.shield+6,0,100);spawnPulseRing();for(let i=enemyShots.length-1;i>=0;i--){const p=enemyShots[i];if(p.position.distanceToSquared(ship.position)<85){explode(p.position,false,false);fx.remove(p);enemyShots.splice(i,1);state.score+=20}}for(const e of [...enemies])if(e.position.distanceToSquared(ship.position)<130)applyEnemyDamage(e,e.userData.type==='boss'?.4:1.1,false);toastMsg('PHASE PULSE');navigator.vibrate?.(18);blip(90,.18,.08,'sawtooth')}
function setStick(px,py){const rect=stickZone.getBoundingClientRect(),baseX=rect.left+74,baseY=rect.bottom-74;let dx=px-baseX,dy=py-baseY;const max=42,mag=Math.hypot(dx,dy)||1;if(mag>max){dx*=max/mag;dy*=max/mag}input.x=clamp(dx/max,-1,1);input.y=clamp(-dy/max,-1,1);stickKnob.style.transform=`translate(${dx}px,${dy}px)`}stickZone.addEventListener('pointerdown',e=>{input.pointer=e.pointerId;stickZone.setPointerCapture(e.pointerId);setStick(e.clientX,e.clientY)});stickZone.addEventListener('pointermove',e=>{if(e.pointerId===input.pointer)setStick(e.clientX,e.clientY)});function releaseStick(e){if(e.pointerId!==input.pointer)return;input.pointer=null;input.x=input.y=0;stickKnob.style.transform='translate(0,0)'}stickZone.addEventListener('pointerup',releaseStick);stickZone.addEventListener('pointercancel',releaseStick);
function fireOn(e){e.preventDefault();if(!state.overheated){state.fire=true;fireBtn.classList.add('active')}audio()}function fireOff(e){e?.preventDefault();state.fire=false;fireBtn.classList.remove('active')}fireBtn.addEventListener('pointerdown',fireOn);fireBtn.addEventListener('pointerup',fireOff);fireBtn.addEventListener('pointercancel',fireOff);fireBtn.addEventListener('pointerleave',e=>{if(e.buttons===0)fireOff(e)});dashBtn.addEventListener('pointerdown',e=>{e.preventDefault();pulse()});
addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Space'].includes(e.code))e.preventDefault();if(e.code==='KeyA'||e.code==='ArrowLeft')input.keyX=-1;if(e.code==='KeyD'||e.code==='ArrowRight')input.keyX=1;if(e.code==='KeyW'||e.code==='ArrowUp')input.keyY=1;if(e.code==='KeyS'||e.code==='ArrowDown')input.keyY=-1;if(e.code==='Space'&&!state.overheated){state.fire=true;fireBtn.classList.add('active')}if(e.code==='ShiftLeft'||e.code==='ShiftRight')pulse()});addEventListener('keyup',e=>{if(['KeyA','KeyD','ArrowLeft','ArrowRight'].includes(e.code))input.keyX=0;if(['KeyW','KeyS','ArrowUp','ArrowDown'].includes(e.code))input.keyY=0;if(e.code==='Space')fireOff(e)});$('#enter').addEventListener('click',startGame);$('#restart').addEventListener('click',startGame);document.addEventListener('visibilitychange',()=>{if(document.hidden)fireOff()});
function resize(){const w=innerWidth,h=innerHeight;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false);composer.setSize(w,h);applyQuality()}addEventListener('resize',resize,{passive:true});
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.034);state.time+=dt;if(state.running){updateShip(dt);updateCombat(dt);updateEnemies(dt);updateProjectiles(dt);updatePickups(dt);updatePulses(dt);updateCamera(dt);updateWorld(dt);updateQuality(dt);updateHud()}else{sky.material.uniforms.uTime.value=state.time;ocean.material.uniforms.uTime.value=state.time;clouds.material.uniforms.uTime.value=state.time;dust.material.uniforms.uTime.value=state.time;if(ship.visible){ship.rotation.y=Math.sin(state.time*.6)*.08;ship.position.y=PLAYER_BASE_Y+Math.sin(state.time*.8)*.12;updateCamera(dt)}}composer.render()}
applyQuality();resize();updateHud();animate();